version: '3.8'

services:
  app:
    build: .
    ports:
      - "8089:8089"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: