name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/geminify
            
            # Stop containers
            docker compose down
            
            # Pull latest changes
            git pull origin main
            
            # Make gradlew executable
            chmod +x ./gradlew
            
            # Build the project
            ./gradlew build -x test
            
            # Build Docker image (force rebuild)
            docker build --no-cache -t geminify:latest .
            
            # Clean up unused Docker resources
            docker system prune -f
            
            # Start containers
            docker compose up -d
            
            # Show status
            docker compose ps